configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/bumpsh-ChristopheDujarric%2Ftest-train-travel-sdk-687560dce1876ebe022141279724c8ea793cf9783dd70c40629fa3571f1c4652.yml
